apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: CloudflareToken
      metadataPolicy: None
      property: DATA