apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: GrafanaSecret
        metadataPolicy: None
        property: username
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: GrafanaSecret
        metadataPolicy: None
        property: password
