apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-backend 
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: vat-backend
  template:
    metadata:
      labels:
        app: vat-backend
    spec:
      initContainers:
      - name: django-migrations
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command: 
        - /bin/sh
        - -c
        - |
          uv run manage.py migrate
        env:
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: {{ .Values.env.db_name }}
        - name: VAT_POSTGRES_USER
          value: {{ .Values.env.db_user }}
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: {{ .Values.env.db_host }}
        - name: VAT_POSTGRES_HOST2
          value: {{ .Values.env.db_host2 }}
        - name: VAT_POSTGRES_PORT
          value: "5432"
        - name: DJANGO_SETTINGS_MODULE
          value: "core.settings.production"
        - name: VAT_KEYCLOAK_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: "password"
      containers:
      - name: backend
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
            cpu: {{ .Values.requests.cpu }}
          limits:
            memory: {{ .Values.limits.memory }}
            cpu: {{ .Values.limits.cpu }}
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: "secretkey"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: "dsn"
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: {{ .Values.env.db_name }}
        - name: VAT_POSTGRES_USER
          value: {{ .Values.env.db_user }}
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: {{ .Values.env.db_host }}
        - name: VAT_POSTGRES_HOST2
          value: {{ .Values.env.db_host2 }}
        - name: VAT_POSTGRES_PORT
          value: "5432"
        - name: DJANGO_SETTINGS_MODULE
          value: "core.settings.production"
        - name: OTEL_SERVICE_NAME
          value: "django-app"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          # Replace 'alloy.monitoring.svc' with your actual Alloy service address
          value: "http://alloy.alloy.svc.cluster.local:4317"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=production,k8s.pod.name=$(K8S_POD_NAME)"
        - name: OTEL_PYTHON_CONTEXT
          value: "contextvars"
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VAT_KEYCLOAK_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: "password"
        volumeMounts:
        - name: modelmount
          mountPath: /mnt/models
        - name: datasetmount
          mountPath: /mnt/datasets
        - name: videomount
          mountPath: /mnt/videos
      imagePullSecrets:
      - name: github-access
      volumes:
      - name: modelmount
        hostPath:
          path: /mnt/models
      - name: datasetmount
        hostPath:
          path: /mnt/datasets
      - name: videomount
        hostPath:
          path: /mnt/videos
