apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-backend 
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: vat-backend
  template:
    metadata:
      labels:
        app: vat-backend
    spec:
      initContainers:
      - name: django-migrations
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command: 
        - /bin/sh
        - -c
        - |
          uv run manage.py migrate
        env:
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: {{ .Values.env.db_name }}
        - name: VAT_POSTGRES_USER
          value: {{ .Values.env.db_user }}
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: {{ .Values.env.db_host }}
        - name: VAT_POSTGRES_PORT
          value: "5432"
        - name: DJANGO_SETTINGS_MODULE
          value: "core.settings.production"
      containers:
      - name: backend
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
            cpu: {{ .Values.requests.cpu }}
          limits:
            memory: {{ .Values.limits.memory }}
            cpu: {{ .Values.limits.cpu }}
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: "secretkey"
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: {{ .Values.env.db_name }}
        - name: VAT_POSTGRES_USER
          value: {{ .Values.env.db_user }}
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: {{ .Values.env.db_host }}
        - name: VAT_POSTGRES_PORT
          value: "5432"
        - name: DJANGO_SETTINGS_MODULE
          value: "core.settings.production"
        volumeMounts:
        - name: modelmount
          mountPath: /mnt/models
        - name: datasetmount
          mountPath: /mnt/datasets
        - name: videomount
          mountPath: /mnt/videos
      imagePullSecrets:
      - name: github-access
      volumes:
      - name: modelmount
        hostPath:
          path: /mnt/models
      - name: datasetmount
        hostPath:
          path: /mnt/datasets
      - name: videomount
        hostPath:
          path: /mnt/videos
