{{- if not .Values.is_dev }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vat-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: vat-backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "700m"
spec:
  ingressClassName: nginx
  rules:
    - host: "vat.berlin-united.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: vat-svc-frontend-bridge
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80
          - path: /schema
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80   
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80
          - path: /_allauth
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80
          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80  
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80 
          - path: /csrf
            pathType: Prefix
            backend:
              service:
                name: vat-svc-backend
                port:
                  number: 80 
  tls:
  - hosts:
    - "vat.berlin-united.com"
    secretName: tls-cert-vat
{{ end }}
