apiVersion: v2
name: grafana
description: VAT Grafana Helm Chart
type: application
version: 0.1.0
appVersion: "0.0.10"

dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 10.5.15