apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-prometheus
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-prometheus
  duration: 2160h
  renewBefore: 360h
  commonName: prometheus.berlin-united.com
  dnsNames:
  - prometheus.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-prometheus
    kind: Issuer