apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prom-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  dataFrom:
    - extract:
        key: PromAuth
        property: auth

