image:
  name: ghcr.io/visual-analytics-toolbox/django_backend
  tag: latest

replicas: 1

env:
  db_name: vat
  db_user: naoth
  db_host: postgres-postgresql.postgres.svc.cluster.local
  db_host2: vat-postgres-rw.vat-backend.svc.cluster.local


requests:
  memory: "4Gi"
  cpu: "10"
limits:
  memory: "6Gi"
  cpu: "10"
