image:
  name: ghcr.io/berlinunited/django_backend
  tag: latest

replicas: 1

is_dev: true

env:
  db_name: vat
  db_user: naoth
  db_host: vat-postgres-rw.vat-backend.svc.cluster.local


requests:
  memory: "4Gi"
  cpu: "4"
limits:
  memory: "6Gi"
  cpu: "6"
