image:
  name: ghcr.io/berlinunited/django_backend
  tag: latest

replicas: 2

env:
  db_name: vat
  db_user: naoth
  db_host: postgres-postgresql.postgres.svc.cluster.local


requests:
  memory: "4Gi"
  cpu: "10"
limits:
  memory: "6Gi"
  cpu: "10"
