label-studio:
  global:
    pgConfig:
      host: "labelstudio-postgres-rw.labelstudio.svc.cluster.local"
      dbName: "labelstudio"
      userName: "labelstudio"
      password:
        secretName: "labelstudio-postgresql"
        secretKey: "password"

    imagePullSecrets:
      - name: github-access

    image:
      registry: ghcr.io
      repository: visual-analytics-toolbox/vat-labelstudio
      tag: autologin_vat_instance
      

    extraEnvironmentVars:
      LABEL_STUDIO_HOST: https://labelstudio.berlin-united.com
      LABEL_STUDIO_USERNAME: email@example.com

  app:
    # there is another ingress for /api
    ingress:
      enabled: true
      className: nginx
      host: "labelstudio.berlin-united.com"
      path: /
      tls:
        - secretName: tls-cert-labelstudio
          hosts:
            - labelstudio.berlin-united.com
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.berlin-united.com/oauth2/start?rd=https://$host$request_uri
        nginx.ingress.kubernetes.io/auth-url: http://oauth-proxy-oauth2-proxy.oauth-proxy.svc.cluster.local/oauth2/auth
        nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
        nginx.ingress.kubernetes.io/auth-response-headers: Authorization

  postgresql:
    enabled: false
