mlflow:
  backendStore:
    postgres:
      enabled: true
      host: mlflow-postgres-rw.mlflow.svc.cluster.local
      port: 5432
      database: mlflow

    existingDatabaseSecret:
      name: mlflow-postgresql
      usernameKey: username
      passwordKey: password

  serviceMonitor:
    enabled: false

  artifactRoot:
    s3:
      enabled: true
      bucket: mlflow
      existingSecret:
        name: "mlflow-minio"
        # -- This is for setting up the key for AWS_ACCESS_KEY_ID secret. If it's set, awsAccessKeyId will be ignored.
        keyOfAccessKeyId: "accessKeyID"
        # -- This is for setting up the key for AWS_SECRET_ACCESS_KEY secret. If it's set, awsSecretAccessKey will be ignored.
        keyOfSecretAccessKey: "accessKeySecret"

  extraEnvVars:
    MLFLOW_S3_ENDPOINT_URL: minio.berlin-united.com
    MLFLOW_SERVER_CORS_ALLOWED_ORIGINS: https://mlflow.berlin-united.com
    MLFLOW_SERVER_ALLOWED_HOSTS: mlflow.berlin-united.com
