beyla:
  config:
    data:
      # Contents of the actual Beyla configuration file
      discovery:
        instrument:
          - k8s_namespace: vat-backend
      routes:
        unmatched: heuristic

  env:
    BEYLA_TRACE_PRINTER: "json"
    BEYLA_LOG_LEVEL: "debug"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.alloy.svc.cluster.local:4318"
