beyla:
  config:
    data:
      # Contents of the actual Beyla configuration file
      discovery:
        instrument:
          - k8s_namespace: vat-backend
      routes:
        unmatched: heuristic
      otel_metrics_export:
        endpoint: http://alloy.alloy.svc.cluster.local:4318
      otel_traces_export:
        endpoint: http://alloy.alloy.svc.cluster.local:4318

  env:
    BEYLA_TRACE_PRINTER: "json"
