apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth-proxy-oauth2-proxy.oauth-proxy.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.berlin-united.com/oauth2/start?rd=https://$host$request_uri
    nginx.ingress.kubernetes.io/auth-method: "GET"
    # 1. THIS IS THE CRITICAL ADDITION
    # This passes the token to the proxy during the auth check
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header Authorization $http_authorization;

    # 2. Keep this to ensure the token also reaches MLflow after passing the proxy
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization $http_authorization;

    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
spec:
  ingressClassName: nginx
  rules:
    - host: "mlflow.berlin-united.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: mlflow
                port:
                  number: 80
  tls:
    - hosts:
        - "mlflow.berlin-united.com"
      secretName: tls-cert-mlflow
